// <auto-generated />
using Highscore_WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Highscore_WebAPI.Migrations
{
    [DbContext(typeof(ScoreDetailContext))]
    [Migration("20220831141610_AddedDistance")]
    partial class AddedDistance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Highscore_WebAPI.Models.ScoreDetail", b =>
                {
                    b.Property<int>("ScoreDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DistanceInMeters")
                        .HasColumnType("int");

                    b.Property<int>("HighScore")
                        .HasColumnType("int");

                    b.Property<string>("ScoreName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ScoreTimeinSec")
                        .HasColumnType("int");

                    b.HasKey("ScoreDetailId");

                    b.ToTable("ScoreDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
